### ISSUE TITLE
[ROADMAP] Beta

### ISSUE THREAD

**Issue by PapyElGringo** [free-explorers/veshell#10]
# Monitor
- [x] Display Shell on multi-monitors
- [x] Split Monitors into several virtual screens
- [x] Automatically create a Virtual Screens for a monitor
- [ ] Configuration capabilities 
- - [ ] Monitor resolution / refresh rate
- - [ ] Monitor positions relatively to others
- - [ ] Mirrored mode
- - [ ] Splitted virtual screens ratio
- - [ ] Select the displayed Virtual Screens among the Virtual Screens configured

# Virtual Screen
- [x]  Manage infinite vertical workspace list 
- [x]  Vertical Panel Widget
- - [x] Workspace List Widget 
   - - [x] Select and display the current workspace selected
   - - [x] Reorder the workspace among the list using drag & drop
   - - [ ] Configure the display icon style from `Hybrid`, `Category` or `Application` mode
- - [ ] Monitor Configuration Widget
- [x] Hotkeys
- - [x] `Meta` Toggle Overview
- - [x] `Meta + W` Select upper workspace
- - [x] `Meta + S` Select lower workspace
- - [ ] `Meta + Shift + W` Reorder current workspace upward
- - [ ] `Meta + Shift + S` Reorder current workspace downward

# Workspace
- [x]  Manage infinite horizontal Persistent Tileable list 
- [x]  Horizontal Panel Widget
- - [x] Persistent Tileable List Widget 
   - - [x] Select and display the current Tileable selected
   - - [x] Reorder the Tileable among the list using drag & drop
   - - [x] Add special Application Launcher Tileable at the end
- - [x] Number of visible Tileable switcher Widget
- - [ ] Resized the proportion of each displayed Tileable
- [x] Hotkeys
- - [x] `Meta + A` Select Tileable on the Left
- - [x] `Meta + D` Select Tileable on the Right
- - [ ] `Meta + Shift + A` Reorder current Tileable to the Left
- - [ ] `Meta + Shift + D` Reorder current Tileable to the Right

# Tileable Application Launcher
- [x] Display a grid of installed application `.desktop`  on the system
- [x] Search Text input to filter the displayed list

# Tileable Persistent Window
- [x] Display either a running `Application Wayland Surface` or a `Configurable Placeholder`
- [x] Display related pop-up and modals contained and on top
- [ ] Handle following Tiled Display Mode `Maximized` , `Full-screen`, `Restrained float-able` 
- [x] Configurable Placeholder Widget 
- - [x] Tap to launch the application
- - [ ] Configure the Tiled Display Mode
- - [ ] Edit the launch arguments
- - [ ] Display the logs of the execution until the Application Surface is Mapped
- [x] Hotkeys
- - [x] `Meta + Q` Close Application if running or Remove Tileable if not running
 
# Overview
- [x] Multi-Purpose search engine
- - [x] Ephemeral Application Launcher
- - [ ] File explorer
- - [ ] Settings explorer
- [x] Helm - System Overview
- - [x] Control Center 
  - - [ ] Media player Control
  - - [ ] Audio Control
  - - [x] Ethernet Network Control
  - - [x] Wifi Network Control
  - - [x] Bluetooth Control 
- - [x] Session Management
  - - [x] Lock Session
  - - [x] Logout Session
  - - [x] Sleep
  - - [x] Reboot
  - - [x] Shutdown
- - [x] System Monitoring
  - - [ ] Battery / Power Usage monitor
  - - [x] Cpu monitor
  - - [x] Memory monitor
  - - [x] Disk usages monitor
- - [x] Global notification list
- [x] Ephemeral Application

# Wayland Server
- [x] Track `Surface` and `Sub Surface` lifecycle
- [x] XWayland protocol extension
- [x] Transpose Toplevel / X11Surface to either `Tileable Persistent Window` or `Ephemeral Window`
- [ ] Manage proper cursor for application state

# Freedesktop compliance
- [x] Polkit Authentication Agent
- [x] Notification Server
- [x] Session management
